CREATE TABLE `kew`.`ipni_new` (
  `id` varchar(50) DEFAULT NULL,
  `authors_t` text,
  `basionym_s_lower` text,
  `basionym_author_s_lower` text,
  `lookup_basionym_id` text,
  `bibliographic_reference_s_lower` text,
  `bibliographic_type_info_s_lower` text,
  `reference_collation_s_lower` text,
  `collection_date_as_text_s_lower` text,
  `collection_day_1_s_lower` text,
  `collection_day_2_s_lower` text,
  `collection_month_1_s_lower` text,
  `collection_month_2_s_lower` text,
  `collection_number_s_lower` text,
  `collection_year_1_s_lower` text,
  `collection_year_2_s_lower` text,
  `collector_team_as_text_t` text,
  `lookup_conserved_against_id` text,
  `lookup_correction_of_id` text,
  `date_created_date` datetime DEFAULT NULL,
  `date_last_modified_date` datetime DEFAULT NULL,
  `distribution_s_lower` text,
  `east_or_west_s_lower` text,
  `family_s_lower` text,
  `taxon_scientific_name_s_lower` text,
  `taxon_sci_name_suggestion` text,
  `genus_s_lower` text,
  `geographic_unit_as_text_s_lower` text,
  `hybrid_b` text,
  `hybrid_genus_b` text,
  `lookup_hybrid_parent_id` text,
  `hybrid_parents_s_lower` text,
  `infra_family_s_lower` text,
  `infra_genus_s_lower` text,
  `infraspecies_s_lower` text,
  `lookup_isonym_of_id` text,
  `lookup_later_homonym_of_id` text,
  `latitude_degrees_s_lower` text,
  `latitude_minutes_s_lower` text,
  `latitude_seconds_s_lower` text,
  `locality_s_lower` text,
  `longitude_degrees_s_lower` text,
  `longitude_minutes_s_lower` text,
  `longitude_seconds_s_lower` text,
  `name_status_s_lower` text,
  `name_status_bot_code_type_s_lower` text,
  `name_status_editor_type_s_lower` text,
  `nomenclatural_synonym_s_lower` text,
  `lookup_nomenclatural_synonym_id` text,
  `north_or_south_s_lower` text,
  `original_basionym_s_lower` text,
  `original_basionym_author_team_s_lower` text,
  `original_hybrid_parentage_s_lower` text,
  `original_remarks_s_lower` text,
  `original_replaced_synonym_s_lower` text,
  `original_taxon_distribution_s_lower` text,
  `lookup_orthographic_variant_of_id` text,
  `other_links_s_lower` text,
  `lookup_parent_id` text,
  `publication_s_lower` text,
  `lookup_publication_id` text,
  `publication_year_i` int DEFAULT NULL,
  `publication_year_full_s_lower` text,
  `publication_year_note_s_lower` text,
  `publishing_author_s_lower` text,
  `rank_s_alphanum` text,
  `reference_t` text,
  `reference_remarks_s_lower` text,
  `remarks_s_lower` text,
  `lookup_replaced_synonym_id` text,
  `lookup_same_citation_as_id` text,
  `score_s_lower` text,
  `species_s_lower` text,
  `species_author_s_lower` text,
  `lookup_superfluous_name_of_id` text,
  `suppressed_b` text,
  `top_copy_b` text,
  `lookup_type_id` text,
  `type_locations_s_lower` text,
  `type_name_s_lower` text,
  `type_remarks_s_lower` text,
  `type_chosen_by_s_lower` text,
  `type_note_s_lower` text,
  `detail_author_team_ids` text,
  `detail_species_author_team_ids` text,
  `page_as_text_s_lower` text,
  `citation_type_s_lower` text,
  `lookup_validation_of_id` text,
  `version_s_lower` text,
  `powo_b` text,
  `sortable` text,
  `family_taxon_name_sortable` text,
  `ipni_wfo_id` varchar(16),
  KEY `created` (`date_created_date`) USING BTREE,
  KEY `modified` (`date_last_modified_date`) USING BTREE,
  KEY `id` (`id`) USING BTREE,
  KEY `year` (`publication_year_i`) USING BTREE

) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
